### ISSUE TITLE
GUI for documents does not load WP 4.8.1 & CiviCRM 4.7.23 & Documents 1.6

### ISSUE THREAD

**Issue by steveschiltz** [CiviCooP/org.civicoop.documents#4]
Hello

I noticed that the GUI for adding documents to a contact (or downloading existing ones) does not load anymore.
I'm using WP 4.8.1, CiviCRM 4.7.23 for WP and the Documents extension 1.6
Instead the resume page of teh contact loads, and the tabs are repeated on top of it as normal hyperlinks

scrshot1: the normal resume of the contact, with the tabs displaying normally
scrshot2: the tab "Documents" has been clicked; the resum reloaded, the content of teh tabs is repeated on top of teh resume, formatted as hyperlinks

The behaviour is the same for contacts with existing documents

Any idea or hint?

Regards

Steve
![scrshot1](https://user-images.githubusercontent.com/9723161/30022049-db286c06-9169-11e7-8a48-9f47da76b848.png)
![scrshot2](https://user-images.githubusercontent.com/9723161/30022048-db26e958-9169-11e7-89c8-e9d823acc73f.png)

**Comment by steveschiltz** [comment]
You may close the issue; the upgrade to v1.6 was only partial.
The extension is working fine

**Comment by jaapjansma** [comment]
Thanks.
