### ISSUE TITLE
Is there any integration with Webform when using Cases

### ISSUE THREAD

**Issue by petednz** [CiviCooP/org.civicoop.documents#7]
We are creating and updating Cases via webform - currently we are adding files on to an Activity

Will this extension let us add documents direct to the Case via 'webform' integration?

**Comment by jaapjansma** [comment]
Yes this same extension contains a drupal module webform_civicrm_documents

**Comment by petednz** [comment]
Jitendra took a look for me and said "I enabled the webform document module provided by this ext but wasn't able to see this via UI or in webform settings. There isn't any documentation available for this module on the ext page. Need to check more to get into code and check/debug."

**Comment by petednz** [comment]
I can see the module in the extension, but it doesn't get listed on my modules page. and drush en fails to work for me. I tried moving the module to /sites/all/modules but drush en still didn't work. feel i am missing something obvious

**Comment by jaapjansma** [comment]
Strange. Could it be something in your drupal installation? The module is for drupal 7
