### ISSUE TITLE
Views integration - has any work be done on this yet?

### ISSUE THREAD

**Issue by petednz** [CiviCooP/org.civicoop.documents#8]

**Comment by jaapjansma** [comment]
Yes. This extension contains a drupal module views_civicrm_documents.

**Comment by petednz** [comment]
ok. happy to add to documentation. when i check my drupal modules it does not get listed, so hard to know if it automatically gets enabled or not. 

jitendra looked at it last night and said "the view module mentioned above provides the document id that is being added to the case. As "civicrm_entity_file" isn't available in views, I think we need to make a little customization within hooks to display file name or a download link of the file."

Are we right that we need to do some more views work so we can have a View based on Cases that will then list (with links) all uploaded documents

**Comment by petednz** [comment]
hmm can't see how to reopen this

**Comment by jaapjansma** [comment]
You can create a view with cases and then link it the CiviCRM Document Case and that one you can link to CiviCRM Document. 
You dont need the civicrm_entity_file.

**Comment by petednz** [comment]
Still struggling. Wondering if you have a View you could upload or screenshot? I have tried using various Relationships - I do have a Field called: (Document ID of document contact) CiviCRM Document: Document Download link (Document Download link)
but i only get that if i use a Relationship, and it simply gives me a 0
I tried just making a link but an example path is /civicrm/file?reset=1&id=48&eid=13. The eid I see is the Document ID of Document Case field, and the 'id' field is the value from civicrm_file - but i don't seem to be able to join that in. And anyway, having a field that is called "document download link' really suggests that I shouldn't be needing to do this.
![image](https://user-images.githubusercontent.com/5800574/32514970-6b336dc4-c463-11e7-92e6-2543b7d38bd2.png)

![image](https://user-images.githubusercontent.com/5800574/32514981-740c477c-c463-11e7-8505-b697b1a2e9aa.png)

![image](https://user-images.githubusercontent.com/5800574/32514988-7abc43ec-c463-11e7-9e96-0083d3de1136.png)

**Comment by petednz** [comment]
maybe i was totally overlooking the checkbox that is on that field!
